# Generated by Django 4.2.4 on 2023-09-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ujumbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ujumbe', models.TextField()),
                ('wapokeaji', models.CharField(blank=True, max_length=80, null=True)),
                ('mjumbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ujumbe_mjumbe', to='users.jumbe')),
                ('mtendaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ujumbe_mtendaji', to='users.mtendaji')),
            ],
        ),
    ]
