# Generated by Django 4.2.4 on 2023-09-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_mjumbe_nyumba_kumi_and_more'),
        ('ujumbe', '0002_alter_ujumbe_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UjumbeUliotumwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nambari_ya_simu', models.CharField(blank=True, max_length=80, null=True)),
                ('mjumbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zilizotumwa_mjumbe', to='users.mjumbe')),
                ('mtendaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zilizotumwa_mtendaji', to='users.mtendaji')),
                ('ujumbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wapokeaji_ujumbe', to='ujumbe.ujumbe')),
            ],
            options={
                'verbose_name_plural': 'jumbeZilizotumwa',
            },
        ),
    ]
