# Generated by Django 4.2.4 on 2023-09-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujumbe', '0003_ujumbeuliotumwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujumbe',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ujumbeuliotumwa',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
