# Generated by Django 4.2.4 on 2023-09-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujumbe', '0006_alter_ujumbeuliotumwa_mjumbe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujumbeuliotumwa',
            name='is_deliverd',
            field=models.BooleanField(default=False),
        ),
    ]
