# Generated by Django 4.2.4 on 2023-09-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujumbe', '0007_ujumbeuliotumwa_is_deliverd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujumbeuliotumwa',
            name='ujumbe',
            field=models.TextField(null=True),
        ),
    ]
