# Generated by Django 4.2.4 on 2023-09-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujumbe', '0008_alter_ujumbeuliotumwa_ujumbe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ujumbeuliotumwa',
            old_name='is_deliverd',
            new_name='is_delivered',
        ),
    ]
