# Generated by Django 4.2.4 on 2023-10-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujumbe', '0009_rename_is_deliverd_ujumbeuliotumwa_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujumbeuliotumwa',
            name='utambulisho_wa_ujumbe',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
