# Generated by Django 4.2.4 on 2023-10-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ujumbe', '0010_ujumbeuliotumwa_utambulisho_wa_ujumbe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujumbe',
            name='mjumbe',
        ),
        migrations.RemoveField(
            model_name='ujumbe',
            name='mtendaji',
        ),
        migrations.RemoveField(
            model_name='ujumbeuliotumwa',
            name='mjumbe',
        ),
        migrations.RemoveField(
            model_name='ujumbeuliotumwa',
            name='mtendaji',
        ),
        migrations.AddField(
            model_name='ujumbe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ujumbe_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ujumbeuliotumwa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zilizotumwa_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
