# Generated by Django 4.2.4 on 2023-10-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_kata_wilaya_alter_mtaa_kata_and_more'),
        ('ujumbe', '0011_remove_ujumbe_mjumbe_remove_ujumbe_mtendaji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujumbe',
            name='kata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.kata'),
        ),
        migrations.AddField(
            model_name='ujumbeuliotumwa',
            name='kata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.kata'),
        ),
    ]
