# Generated by Django 4.2.4 on 2023-09-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jumbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
                ('nambari_ya_simu', models.CharField(blank=True, max_length=200, null=True)),
                ('barua_pepe', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mkoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mtaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
                ('kata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kata')),
            ],
        ),
        migrations.CreateModel(
            name='Mtendaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
                ('nambari_ya_simu', models.CharField(blank=True, max_length=200, null=True)),
                ('barua_pepe', models.CharField(blank=True, max_length=200, null=True)),
                ('kata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtendaji_kata', to='users.kata')),
                ('mkoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtendaji_mkoa', to='users.mkoa')),
                ('mtaa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtendaji_mtaa', to='users.mtaa')),
            ],
        ),
        migrations.CreateModel(
            name='Nchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
                ('mkoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mkoa')),
            ],
        ),
        migrations.CreateModel(
            name='Mwananchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
                ('nambari_ya_simu', models.CharField(blank=True, max_length=200, null=True)),
                ('barua_pepe', models.CharField(blank=True, max_length=200, null=True)),
                ('kata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwananchi_kata', to='users.kata')),
                ('mjumbe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwananchi_mjumbe', to='users.jumbe')),
                ('mkoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwananchi_mkoa', to='users.mkoa')),
                ('mtaa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwananchi_mtaa', to='users.mtaa')),
                ('mtendaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwananchi_mtendaji', to='users.mtendaji')),
                ('nchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwananchi_nchi', to='users.nchi')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwananchi_wilaya', to='users.wilaya')),
            ],
        ),
        migrations.AddField(
            model_name='mtendaji',
            name='nchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtendaji_nchi', to='users.nchi'),
        ),
        migrations.AddField(
            model_name='mtendaji',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtendaji_wilaya', to='users.wilaya'),
        ),
        migrations.AddField(
            model_name='mkoa',
            name='nchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nchi'),
        ),
        migrations.AddField(
            model_name='kata',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.wilaya'),
        ),
        migrations.AddField(
            model_name='jumbe',
            name='kata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumbe_kata', to='users.kata'),
        ),
        migrations.AddField(
            model_name='jumbe',
            name='mkoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumbe_mkoa', to='users.mkoa'),
        ),
        migrations.AddField(
            model_name='jumbe',
            name='mtaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumbe_mtaa', to='users.mtaa'),
        ),
        migrations.AddField(
            model_name='jumbe',
            name='nchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumbe_nchi', to='users.nchi'),
        ),
        migrations.AddField(
            model_name='jumbe',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumbe_wilaya', to='users.wilaya'),
        ),
    ]
