# Generated by Django 4.2.4 on 2023-09-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujumbe', '0002_alter_ujumbe_options'),
        ('users', '0002_alter_mkoa_nchi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jumbe',
            new_name='Mjumbe',
        ),
        migrations.AlterModelOptions(
            name='kata',
            options={'verbose_name_plural': 'Kata'},
        ),
        migrations.AlterModelOptions(
            name='mjumbe',
            options={'verbose_name_plural': 'Wajumbe'},
        ),
        migrations.AlterModelOptions(
            name='mkoa',
            options={'verbose_name_plural': 'Mikoa'},
        ),
        migrations.AlterModelOptions(
            name='mtaa',
            options={'verbose_name_plural': 'Mitaa'},
        ),
        migrations.AlterModelOptions(
            name='mtendaji',
            options={'verbose_name_plural': 'Watendaji'},
        ),
        migrations.AlterModelOptions(
            name='mwananchi',
            options={'verbose_name_plural': 'Wananchi'},
        ),
        migrations.AlterModelOptions(
            name='nchi',
            options={'verbose_name_plural': 'Nchi'},
        ),
        migrations.AlterModelOptions(
            name='wilaya',
            options={'verbose_name_plural': 'Wilaya'},
        ),
    ]
