# Generated by Django 4.2.4 on 2023-09-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_jumbe_mjumbe_alter_kata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mjumbe',
            name='mtendaji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mjumbe_mtendaji', to='users.mtendaji'),
        ),
    ]
