# Generated by Django 4.2.4 on 2023-09-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mjumbe_mtendaji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkoa',
            name='nchi',
            field=models.ForeignKey(default='Tanzania', on_delete=django.db.models.deletion.CASCADE, related_name='mkoa_ya_nchi', to='users.nchi'),
        ),
    ]
