# Generated by Django 4.2.4 on 2023-09-27 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mkoa_nchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mjumbe',
            name='kata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mjumbe_kata', to='users.kata'),
        ),
        migrations.AlterField(
            model_name='mjumbe',
            name='mkoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mjumbe_mkoa', to='users.mkoa'),
        ),
        migrations.AlterField(
            model_name='mjumbe',
            name='mtaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mjumbe_mtaa', to='users.mtaa'),
        ),
        migrations.AlterField(
            model_name='mjumbe',
            name='nchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mjumbe_nchi', to='users.nchi'),
        ),
        migrations.AlterField(
            model_name='mjumbe',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mjumbe_wilaya', to='users.wilaya'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='mkoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilaya_mikoa', to='users.mkoa'),
        ),
        migrations.CreateModel(
            name='NyumbaKumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
                ('mtaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mtaa')),
            ],
            options={
                'verbose_name_plural': 'NyumbaKumi',
            },
        ),
        migrations.CreateModel(
            name='Mwenyekiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(blank=True, max_length=200, null=True)),
                ('nambari_ya_simu', models.CharField(blank=True, max_length=200, null=True)),
                ('barua_pepe', models.CharField(blank=True, max_length=200, null=True)),
                ('kata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwenyekiti_kata', to='users.kata')),
                ('mkoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwenyekiti_mkoa', to='users.mkoa')),
                ('mtaa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwenyekiti_mtaa', to='users.mtaa')),
                ('mtendaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwenyekiti_mtendaji', to='users.mtendaji')),
                ('nchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwenyekiti_nchi', to='users.nchi')),
                ('nyumba_kumi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwenyekiti_nyumba_kumi', to='users.nyumbakumi')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwenyekiti_wilaya', to='users.wilaya')),
            ],
            options={
                'verbose_name_plural': 'Wenyeviti',
            },
        ),
        migrations.AddField(
            model_name='mjumbe',
            name='mwenyekiti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mjumbe_mwenyekiti', to='users.mwenyekiti'),
        ),
        migrations.AddField(
            model_name='mjumbe',
            name='nyumba_kumi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mjumbe_nyumba_kumi', to='users.nyumbakumi'),
        ),
        migrations.AddField(
            model_name='mwananchi',
            name='nyumba_kumi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwananchi_nyumba_kumi', to='users.nyumbakumi'),
        ),
    ]
