# Generated by Django 4.2.4 on 2023-09-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_mjumbe_kata_alter_mjumbe_mkoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mjumbe',
            name='nyumba_kumi',
        ),
        migrations.RemoveField(
            model_name='mwananchi',
            name='nyumba_kumi',
        ),
        migrations.AddField(
            model_name='mjumbe',
            name='barozi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mjumbe_barozi', to='users.nyumbakumi'),
        ),
        migrations.AddField(
            model_name='mwananchi',
            name='barozi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwananchi_barozi', to='users.nyumbakumi'),
        ),
    ]
