# Generated by Django 4.2.4 on 2023-09-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_mjumbe_user_mtendaji_user_mwenyekiti_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kata',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kata_wilaya', to='users.wilaya'),
        ),
        migrations.AlterField(
            model_name='mtaa',
            name='kata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitaa_kata', to='users.kata'),
        ),
        migrations.AlterField(
            model_name='nyumbakumi',
            name='mtaa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barozi_mitaa', to='users.mtaa'),
        ),
    ]
