# Generated by Django 4.2.4 on 2023-10-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_kata_wilaya_alter_mtaa_kata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mjumbe',
            name='jinsia',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='mtendaji',
            name='jinsia',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='mwananchi',
            name='jinsia',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='mwenyekiti',
            name='jinsia',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
