# Generated by Django 4.2.4 on 2023-10-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_mjumbe_jinsia_mtendaji_jinsia_mwananchi_jinsia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mwenyekiti',
            old_name='nyumba_kumi',
            new_name='barozi',
        ),
    ]
