# Generated by Django 4.2.4 on 2023-10-05 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_nyumba_kumi_mwenyekiti_barozi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtendaji',
            name='barozi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtendaji_ubarozi', to='users.nyumbakumi'),
        ),
    ]
