# Generated by Django 4.2.4 on 2023-10-02 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tangazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UjumbeWaTangazoUlioFika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ujumbe', models.TextField(null=True)),
                ('eneo', models.CharField(max_length=255, null=True)),
                ('utambulisho_wa_ujumbe', models.CharField(max_length=255, null=True)),
                ('nambari_ya_simu', models.CharField(blank=True, max_length=80, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limefika_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UumbeZaTangazoZilizoFika',
            },
        ),
        migrations.CreateModel(
            name='UjumbeWaTangazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ujumbe', models.TextField()),
                ('eneo', models.CharField(max_length=255, null=True)),
                ('wapokeaji', models.CharField(blank=True, max_length=80, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tangazo_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jumbe',
            },
        ),
    ]
