# Generated by Django 4.2.4 on 2023-10-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ujumbewatangazo',
            options={'verbose_name_plural': 'JumbeZaMatangazo'},
        ),
        migrations.AlterModelOptions(
            name='ujumbewatangazouliofika',
            options={'verbose_name_plural': 'JumbeZaTangazoZilizoFika'},
        ),
    ]
