# Generated by Django 4.2.4 on 2023-10-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_tangazo_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tangazo',
            options={'verbose_name_plural': 'Matangazo'},
        ),
        migrations.AddField(
            model_name='tangazo',
            name='kwa_ajili_ya',
            field=models.CharField(choices=[('wote', 'wote'), ('wanaume', 'wanaume'), ('wanawake', 'wanawake')], max_length=50, null=True),
        ),
    ]
