# Generated by Django 4.2.4 on 2023-10-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_tangazo_options_tangazo_kwa_ajili_ya'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaeneoYaTangazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orodha_ya_kutangazia', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
