# Generated by Django 4.2.4 on 2023-10-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_maeneoyatangazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tangazo',
            name='ukanda_gani',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
    ]
