# Generated by Django 4.2.4 on 2023-10-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_tangazo_ukanda_gani'),
    ]

    operations = [
        migrations.AddField(
            model_name='tangazo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
