# Generated by Django 4.2.4 on 2023-10-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_tangazo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='maeneoyatangazo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
